version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  web:1 .
      - docker tag web:1 998441165748.dkr.ecr.us-east-2.amazonaws.com/madd
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 998441165748.dkr.ecr.us-east-2.amazonaws.com/madd
